---
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Modules\Hephaistos\:
        resource: '%kernel.project_dir%/src/Modules/Hephaistos/'
        exclude:
            - '../../Message'
            - '../../Model'
            - '../../Repository'
            - '../../Resource'

    App\Modules\Hephaistos\Handler\DailyRoutineHandler:
        arguments:
            $apiMode: "%apimode%"
            $playerInactiveTimeLimit: "%zeus.player.inactive_time_limit%"
            $playerGlobalInactiveTime: "%zeus.player.global_inactive_time%"
            $notificationsReadTimeout: "%hermes.notifications.timeout.read%"
            $notificationsUnreadTimeout: "%hermes.notifications.timeout.unread%"
