---
parameters:
    zeus.player.base_level: 1250
    zeus.player.base_commander_level: 100
    zeus.player.base_ap: 10
    zeus.player.coeff_ap: 5

    zeus.player.tax_coeff: 1

    zeus.player.ally_inactive_time: 168     # 7 days
    zeus.player.global_inactive_time: 360   # 15 days
    zeus.player.inactive_time_limit: 600    # 25 days

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Asylamba\Modules\Zeus\Helper\:
        resource: '%root_path%/system/Modules/Zeus/Helper/*'

    Asylamba\Modules\Zeus\Manager\:
        resource: '%root_path%/system/Modules/Zeus/Manager/*'

    Asylamba\Modules\Zeus\Manager\PlayerManager:
        arguments:
            $playerBaseLevel: "%zeus.player.base_level%"
            $playerTaxCoeff: "%zeus.player.tax_coeff%"
            $serverId: "%server_id%"
            $gaiaId: '%id_gaia%'
