---
parameters:
    # routes commerciales
    athena.trade.route.cancellation_refund: 0.8	# 80% de crédits rendu si on annule la route avant qu'elle soit acceptée
    athena.trade.route.sector_bonus: 1.1
    athena.trade.route.color_bonus: 1.5
    athena.trade.experience_coeff: 0.1

    # pourcentage de ressources rendues lors
    # de l'annulation d'une construction de batiment ou de vaisseau
    athena.building.building_queue_resource_refund: 0.5 # 50%
    athena.building.ship_queue_resource_refund: 0.5 # 50%

    # commercialRoute statement
    athena.trade.route.proposed: 0
    athena.trade.route.active: 1
    athena.trade.route.stand_by: 2

    # type of base constants
    athena.obm.change_type_min_level: 20 # minimal generator level
    athena.obm.capital_min_level: 35 # minimal generator level to build a capital base

services:
    athena.building_queue_manager:
        class: Asylamba\Modules\Athena\Manager\BuildingQueueManager
        arguments:
            - "@database"
            
    athena.commercial_route_manager:
        class: Asylamba\Modules\Athena\Manager\CommercialRouteManager
        arguments:
            - "@database"
            
    athena.commercial_shipping_manager:
        class: Asylamba\Modules\Athena\Manager\CommercialShippingManager
        arguments:
            - "@database"
            - "@athena.orbital_base_manager"
            - "@hermes.notification_manager"
            - "@app.session"
            
    athena.commercial_tax_manager:
        class: Asylamba\Modules\Athena\Manager\CommercialTaxManager
        arguments:
            - "@database"
            
    athena.orbital_base_manager:
        class: Asylamba\Modules\Athena\Manager\OrbitalBaseManager
        arguments:
            - "@database"
            - "@athena.building_queue_manager"
            - "@athena.ship_queue_manager"
            - "@promethee.technology_queue_manager"
            - "@promethee.technology_manager"
            - "@promethee.technology_helper"
            - "@athena.commercial_shipping_manager"
            - "@athena.commercial_route_manager"
            - "@athena.transaction_manager"
            - "@gaia.galaxy_color_manager"
            - "@zeus.player_manager"
            - "@zeus.player_bonus_manager"
            - "@athena.recycling_mission_manager"
            - "@athena.recycling_log_manager"
            - "@gaia.place_manager"
            - "@ares.commander_manager"
            - "@hermes.notification_manager"
            - "@athena.orbital_base_helper"
            - "@ctc"
            - "@app.session"
            
    athena.orbital_base_helper:
        class: Asylamba\Modules\Athena\Helper\OrbitalBaseHelper
        arguments:
            - "@promethee.technology_helper"
            
    athena.recycling_log_manager:
        class: Asylamba\Modules\Athena\Manager\RecyclingLogManager
        arguments:
            - "@database"
            
    athena.recycling_mission_manager:
        class: Asylamba\Modules\Athena\Manager\RecyclingMissionManager
        arguments:
            - "@database"
            
    athena.ship_queue_manager:
        class: Asylamba\Modules\Athena\Manager\ShipQueueManager
        arguments:
            - "@database"
            
    athena.ship_helper:
        class: Asylamba\Modules\Athena\Helper\ShipHelper
        arguments:
            - "@app.session"
            - "@athena.orbital_base_helper"
            - "@promethee.technology_helper"
            - "@athena.ship_queue_manager"
            
    athena.transaction_manager:
        class: Asylamba\Modules\Athena\Manager\TransactionManager
        arguments:
            - "@database"
            - "@athena.commercial_tax_manager"
            - "@app.session"
